# Generated by Django 2.1.4 on 2019-03-13 15:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_heading',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
