# Generated by Django 2.1.4 on 2019-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_page_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_heading',
            field=models.CharField(max_length=100),
        ),
    ]
